wandb_version: 1

region:
  desc: null
  value: Southeast Asia
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.2
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690712290.068428
    t:
      1:
      - 1
      - 5
      - 8
      - 30
      - 53
      - 55
      2:
      - 1
      - 5
      - 8
      - 30
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.2
      8:
      - 3
      - 5
